kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
        group_by: [Alertname]
        group_interval: 30s
        repeat_interval: 30s
        # Send all notifications to me.
        receiver: email-me
    receivers:
    - name: email-me
      email_configs:
      - send_resolved: true
        to: kannadhasan@iplon.in
        from: naveenkumar@iplon.in
        smarthost: smtp.yandex.com:465
        auth_username: "naveenkumar@iplon.in"
        auth_identity: "naveenkumar@iplon.in"
        auth_password: "iplon321"
