groups:
- name: my-group
  rules:
  - alert: ContainerRestartAlert
    expr: kube_pod_container_status_restarts_total > 3
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.container }} restarted in pod {{ $labels.pod }}."
      description: "The {{ $labels.container }} container in pod {{ $labels.pod }} has restarted."

